### ISSUE TITLE
i have some questions

### ISSUE THREAD

**Issue by hundunzhidian** [GiyoMoon/steam-server-query#4]
first ,this libriary is very nice.i made a library like this by Java.but ,i have two questions or suggestions
1、i  crash one error like this
`TypeError: buffer.readBigInt64LE is not a function`
from infoResponse.gameId
2、this library has a2s_info、a2s_players、a2s_rule，and can u add rcon protocol？

**Comment by GiyoMoon** [comment]
Hey, thanks! I appreciate that you like this library :)
Regarding your questions:
1. You probably are using an old version of Node.JS which doesn't support BigInt, please check the version and update it accordingly
2. No, I currently don't have plans to implement the rcon protocol.

I'm closing this issue but feel free to re-open it if you have any follow up questions :)
